// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMR3gSaQKLgMKKj7_hIt8GsjW7sk6Txgo',
    appId: '1:712199168959:web:044b633cabdd058910f70a',
    messagingSenderId: '712199168959',
    projectId: 'flutter-univery-2022',
    authDomain: 'flutter-univery-2022.firebaseapp.com',
    storageBucket: 'flutter-univery-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY4D95p-VuiBoqdv4uN5UjNf3lKoQml5k',
    appId: '1:712199168959:android:69cbd2f1e53c969a10f70a',
    messagingSenderId: '712199168959',
    projectId: 'flutter-univery-2022',
    storageBucket: 'flutter-univery-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCzayPPVsMwZyqltcy3erAz_FUfSuDYbk',
    appId: '1:712199168959:ios:b98f81ce5688bcf410f70a',
    messagingSenderId: '712199168959',
    projectId: 'flutter-univery-2022',
    storageBucket: 'flutter-univery-2022.appspot.com',
    iosClientId: '712199168959-5cs2hou5vtcjfqsf2c61jfbnq32nv9jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.univeryFlutter2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCzayPPVsMwZyqltcy3erAz_FUfSuDYbk',
    appId: '1:712199168959:ios:b98f81ce5688bcf410f70a',
    messagingSenderId: '712199168959',
    projectId: 'flutter-univery-2022',
    storageBucket: 'flutter-univery-2022.appspot.com',
    iosClientId: '712199168959-5cs2hou5vtcjfqsf2c61jfbnq32nv9jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.univeryFlutter2022',
  );
}
